version: 2.1

orbs:
    docker: circleci/docker@1.2.1
    gcp-gke: circleci/gcp-gke@1.1.0
    gcp-gcr: circleci/gcp-gcr@0.12.0
    # cypress: cypress-io/cypress@1

jobs:
    deploy:
        description: Deploy application to Google Kubernetes Engine
        machine: true
        parameters:
            cluster:
                description: |
                    Name of gke cluster
                type: string
            container:
                description: |
                    Name of docker container with organization
                type: string
            deployment:
                description: |
                    Name of k8 deployment
                type: string
            image:
                description: |
                    Name of docker image with organization
                type: string
            tag:
                description: |
                    Docker image tag
                type: string
            namespace:
                description: |
                    k8s namespace
                type: string
        steps:
            - gcp-gke/install
            - gcp-gke/update-kubeconfig-with-credentials:
                  cluster: << parameters.cluster >>
                  perform-login: true
            - gcp-gke/rollout-image:
                  cluster: << parameters.cluster >>
                  container: << parameters.container >>
                  deployment: << parameters.deployment >>
                  image: << parameters.image >>
                  tag: << parameters.tag >>
                  namespace: << parameters.namespace >>

workflows:
    docker-build-push-deploy-dev:
        jobs:
            - gcp-gcr/build-and-push-image:
                  image: TODO_APP_NAME
                  tag: 0.0.1
                  registry-url: gcr.io
                  filters:
                      branches:
                          only:
                              - dev
            - deploy:
                  cluster: TODO_ORGANIZATION
                  container: TODO_APP_NAME
                  deployment: TODO_APP_NAME
                  image: gcr.io/TODO_GCLOUD_PROJECT_ID/TODO_APP_NAME
                  namespace: default
                  tag: 0.0.1
                  filters:
                      branches:
                          only:
                              - dev
                  requires:
                      - gcp-gcr/build-and-push-image
            # - cypress/install:
            #     yarn: true
            #     filters:
            #       branches:
            #         only:
            #           - dev
            #     requires:
            #       - deploy
            # - cypress/run:
            #     yarn: true
            #     filters:
            #       branches:
            #         only:
            #           - dev
            #     requires:
            #       - cypress/install
            #     start: 'yarn start'
