apiVersion: v1
kind: Service
metadata:
    labels:
        app: TODO_APP_NAME
    name: TODO_APP_NAME
spec:
    ports:
        - port: 3000
          targetPort: 3000
          protocol: TCP
    selector:
        app: TODO_APP_NAME
